### ISSUE TITLE
Use GithubActions

### ISSUE THREAD

**Issue by OskarStark** [twigphp/Twig#3428]
### Create pull requests - @OskarStark 

* [x] PR for **GithubActions** for `1.x` branch #3429
* [x] PR for **DOCtor-RST** + **Sphinx build** for `1.x` branch #3430
* [x] PR for **GithubActions** for `2.x` branch #3427
* [x] PR for **DOCtor-RST** for `2.x` branch #3434
* [x] PR for **GithubActions** for `3.x` branch #3419
* [x] PR for **DOCtor-RST** for `3.x` branch #3417

### Merge and upmerge pull requests in this order
* [x] merge #3429 #3430 - @fabpot 
* [x] upmerge `1.x` -> `2.x` - @fabpot 
* [x] rebase #3427 & #3434 onto `2.x`- @OskarStark 
* [x] merge #3427 #3434 - @fabpot 
* [x] upmerge `2.x` -> `3.x` - @fabpot 
* [x] rebase #3419 & #3417 onto `3.x`- @OskarStark 
* [x] merge #3419 #3417 - @fabpot
